- name: Create "docker" group
  ansible.builtin.group:
   name: docker
   state: present

- name: Add remote "ubuntu" user to "docker" group
  ansible.builtin.user:
   name: ubuntu
   group: docker
   append: true